[program:neko-wayland]
command=/usr/bin/neko serve --server.static /var/www --server.bind 0.0.0.0:8080
autostart=false
autorestart=true
startsecs=0
environment=PULSE_SERVER="unix:/tmp/pulse/native",NEKO_DESKTOP_WAYLAND="true",NEKO_CAPTURE_VIDEO_WAYLAND="true",NEKO_CAPTURE_VIDEO_WAYLAND_RECORDER="wf-recorder",NEKO_DESKTOP_WAYLAND_RESIZE_COMMAND="wlr-randr",NEKO_DESKTOP_WAYLAND_OUTPUT="HEADLESS-1"
stdout_logfile=/var/log/supervisord/neko-wayland
redirect_stderr=true
