// Package browserlocation describes the explicit locale and timezone values
// that the browser and image shipped together can apply.
package browserlocation

import (
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"slices"
	"strings"
)

//go:embed capabilities.json
var capabilitiesJSON []byte

// Capabilities is generated by running the built browser inside the image
// (TestBrowserLocationCapabilities in server/e2e). A locale is listed when the
// browser's Intl.DateTimeFormat and Intl.NumberFormat resolve exactly that tag
// and Intl.Collator resolves it or a parent obtained by removing subtags,
// because collation data is mostly per language. A timezone is listed when the
// image ships its zoneinfo file and the browser's Intl accepts the identifier.
type Capabilities struct {
	// Version identifies the browser, the image tzdata and the lists.
	Version   string   `json:"version"`
	Browser   string   `json:"browser"`
	TZData    string   `json:"tzdata"`
	Locales   []string `json:"locales"`
	TimeZones []string `json:"timezones"`
}

var current = mustParse(capabilitiesJSON)

// Current returns the capabilities of the browser and image this binary ships in.
func Current() Capabilities {
	return current
}

// New builds sorted capabilities and derives their version.
func New(browser, tzdata string, locales, timezones []string) Capabilities {
	c := Capabilities{
		Browser:   browser,
		TZData:    tzdata,
		Locales:   slices.Compact(slices.Sorted(slices.Values(locales))),
		TimeZones: slices.Compact(slices.Sorted(slices.Values(timezones))),
	}
	c.Version = c.version()
	return c
}

// SupportsLocale reports whether tag is an accepted canonical locale.
func (c Capabilities) SupportsLocale(tag string) bool {
	_, found := slices.BinarySearch(c.Locales, tag)
	return found
}

// SupportsTimeZone reports whether id is an accepted timezone identifier.
func (c Capabilities) SupportsTimeZone(id string) bool {
	_, found := slices.BinarySearch(c.TimeZones, id)
	return found
}

func (c Capabilities) version() string {
	sum := sha256.Sum256([]byte(strings.Join(c.Locales, ",") + "\n" + strings.Join(c.TimeZones, ",")))
	return fmt.Sprintf("%s+tzdata-%s+%s", c.Browser, c.TZData, hex.EncodeToString(sum[:8]))
}

func mustParse(data []byte) Capabilities {
	var c Capabilities
	if err := json.Unmarshal(data, &c); err != nil {
		panic(fmt.Sprintf("decode browser location capabilities: %v", err))
	}
	if !slices.IsSorted(c.Locales) || !slices.IsSorted(c.TimeZones) || c.Version != c.version() {
		panic("browser location capabilities are not normalized; regenerate them")
	}
	return c
}
