package cdpmonitor

import "strings"

// Explicit subset of Chromium net/base/net_error_list.h, plus two fallbacks.
// Preseed every series so a first failure can be diffed against a scraped zero.
// Index 0 is canceled=false, index 1 is canceled=true.
var networkFailureZeros = map[string][2]uint64{
	"ERR_FAILED": {}, "ERR_ABORTED": {}, "ERR_TIMED_OUT": {},
	"ERR_ACCESS_DENIED": {}, "ERR_INSUFFICIENT_RESOURCES": {},
	"ERR_BLOCKED_BY_CLIENT": {}, "ERR_BLOCKED_BY_ADMINISTRATOR": {},
	"ERR_BLOCKED_BY_RESPONSE": {}, "ERR_BLOCKED_BY_CSP": {}, "ERR_BLOCKED_BY_ORB": {},
	"ERR_CLEARTEXT_NOT_PERMITTED": {}, "ERR_NETWORK_ACCESS_REVOKED": {},
	"ERR_BLOCKED_BY_LOCAL_NETWORK_ACCESS_CHECKS": {}, "ERR_LOCAL_NETWORK_PERMISSION_MISSING": {},
	"ERR_NETWORK_CHANGED": {}, "ERR_INTERNET_DISCONNECTED": {},
	"ERR_CONNECTION_CLOSED": {}, "ERR_CONNECTION_RESET": {}, "ERR_CONNECTION_REFUSED": {},
	"ERR_CONNECTION_ABORTED": {}, "ERR_CONNECTION_FAILED": {}, "ERR_CONNECTION_TIMED_OUT": {},
	"ERR_ADDRESS_INVALID": {}, "ERR_ADDRESS_UNREACHABLE": {}, "ERR_NETWORK_ACCESS_DENIED": {},
	"ERR_NAME_NOT_RESOLVED": {}, "ERR_NAME_RESOLUTION_FAILED": {},
	"ERR_DNS_MALFORMED_RESPONSE": {}, "ERR_DNS_SERVER_REQUIRES_TCP": {}, "ERR_DNS_TIMED_OUT": {},
	"ERR_DNS_SECURE_RESOLVER_HOSTNAME_RESOLUTION_FAILED": {}, "ERR_DNS_REQUEST_CANCELLED": {},
	"ERR_SSL_PROTOCOL_ERROR": {}, "ERR_SSL_VERSION_OR_CIPHER_MISMATCH": {},
	"ERR_SSL_CLIENT_AUTH_CERT_NEEDED": {}, "ERR_BAD_SSL_CLIENT_AUTH_CERT": {},
	"ERR_SSL_PINNED_KEY_NOT_IN_CERT_CHAIN": {},
	"ERR_CERT_COMMON_NAME_INVALID":         {}, "ERR_CERT_DATE_INVALID": {}, "ERR_CERT_AUTHORITY_INVALID": {},
	"ERR_CERT_CONTAINS_ERRORS": {}, "ERR_CERT_NO_REVOCATION_MECHANISM": {},
	"ERR_CERT_UNABLE_TO_CHECK_REVOCATION": {}, "ERR_CERT_REVOKED": {}, "ERR_CERT_INVALID": {},
	"ERR_CERT_WEAK_SIGNATURE_ALGORITHM": {}, "ERR_CERT_NON_UNIQUE_NAME": {}, "ERR_CERT_WEAK_KEY": {},
	"ERR_CERT_NAME_CONSTRAINT_VIOLATION": {}, "ERR_CERT_VALIDITY_TOO_LONG": {},
	"ERR_CERT_KNOWN_INTERCEPTION_BLOCKED": {},
	"ERR_PROXY_CONNECTION_FAILED":         {}, "ERR_TUNNEL_CONNECTION_FAILED": {},
	"ERR_PROXY_AUTH_UNSUPPORTED": {}, "ERR_PROXY_AUTH_REQUESTED": {}, "ERR_PROXY_CERTIFICATE_INVALID": {},
	"ERR_MANDATORY_PROXY_CONFIGURATION_FAILED": {}, "ERR_PROXY_UNABLE_TO_CONNECT_TO_DESTINATION": {},
	"ERR_SOCKS_CONNECTION_FAILED": {}, "ERR_SOCKS_CONNECTION_HOST_UNREACHABLE": {},
	"ERR_HTTP2_PROTOCOL_ERROR": {}, "ERR_HTTP2_SERVER_REFUSED_STREAM": {}, "ERR_HTTP2_PING_FAILED": {},
	"ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY": {}, "ERR_HTTP2_FLOW_CONTROL_ERROR": {},
	"ERR_HTTP2_FRAME_SIZE_ERROR": {}, "ERR_HTTP2_COMPRESSION_ERROR": {}, "ERR_HTTP2_STREAM_CLOSED": {},
	"ERR_INCOMPLETE_HTTP2_HEADERS": {}, "ERR_HTTP2_RST_STREAM_NO_ERROR_RECEIVED": {},
	"ERR_QUIC_PROTOCOL_ERROR": {}, "ERR_QUIC_HANDSHAKE_FAILED": {}, "ERR_QUIC_CERT_ROOT_NOT_KNOWN": {},
	"ERR_EMPTY_RESPONSE": {}, "ERR_CONTENT_LENGTH_MISMATCH": {}, "ERR_INCOMPLETE_CHUNKED_ENCODING": {},
	"ERR_CONTENT_DECODING_FAILED": {}, "ERR_INVALID_RESPONSE": {}, "ERR_TOO_MANY_REDIRECTS": {},
	"ERR_UNSAFE_REDIRECT": {}, "ERR_UNSAFE_PORT": {}, "ERR_INVALID_URL": {}, "ERR_UNKNOWN_URL_SCHEME": {},
	"other": {}, "unknown": {},
}

func networkErrorCode(errorText string) string {
	if errorText == "" {
		return "unknown"
	}
	code, prefixed := strings.CutPrefix(errorText, "net::")
	if prefixed && strings.HasPrefix(code, "ERR_") {
		if _, known := networkFailureZeros[code]; known {
			return code
		}
	}
	return "other"
}
