package devtoolsproxy

import (
	"encoding/json"
	"os"
	"reflect"
	"sort"
	"strings"
	"testing"

	"github.com/ghodss/yaml"
)

var rawMessageType = reflect.TypeOf(json.RawMessage{})

// The inventory test compares the sanitizers against this repo's own OpenAPI
// enum, which is a second copy of the same list and so cannot notice a
// canonical method or argument nobody handled. These tests compare against the
// pinned protocol instead, by way of two checked-in files:
//
//   - testdata/cdp_protocol_pinned.json, generated by scripts/cdpmanifest from
//     devtools-protocol at the pinned commit: every argument of every
//     supported command, including the fields of the object types they carry.
//   - testdata/cdp_arguments.yaml, the decision for each of those arguments.
//
// Between them, an argument added upstream becomes a decision someone has to
// record, and a decision that stops matching the code fails here.

const (
	protocolSnapshotPath = "testdata/cdp_protocol_pinned.json"
	argumentManifestPath = "testdata/cdp_arguments.yaml"
)

type protocolSnapshot struct {
	Commit    string              `json:"commit"`
	Permalink string              `json:"permalink"`
	Commands  map[string][]string `json:"commands"`
}

// argumentDecision is "retained" as a bare string, or a mapping carrying the
// reason it is redacted.
type argumentDecision struct {
	Redacted string `json:"redacted"`
}

func loadProtocolSnapshot(t *testing.T) protocolSnapshot {
	t.Helper()
	raw, err := os.ReadFile(protocolSnapshotPath)
	if err != nil {
		t.Fatalf("read protocol snapshot: %v", err)
	}
	var snap protocolSnapshot
	if err := json.Unmarshal(raw, &snap); err != nil {
		t.Fatalf("parse protocol snapshot: %v", err)
	}
	if len(snap.Commands) == 0 {
		t.Fatal("protocol snapshot is empty, so these tests prove nothing")
	}
	return snap
}

// loadArgumentManifest returns method -> argument -> decision, with retained
// arguments mapping to an empty decision.
func loadArgumentManifest(t *testing.T) map[string]map[string]argumentDecision {
	t.Helper()
	raw, err := os.ReadFile(argumentManifestPath)
	if err != nil {
		t.Fatalf("read argument manifest: %v", err)
	}
	var loose map[string]map[string]json.RawMessage
	if err := yaml.Unmarshal(raw, &loose); err != nil {
		t.Fatalf("parse argument manifest: %v", err)
	}
	out := make(map[string]map[string]argumentDecision, len(loose))
	for method, args := range loose {
		out[method] = map[string]argumentDecision{}
		for arg, value := range args {
			var word string
			if err := json.Unmarshal(value, &word); err == nil {
				if word != "retained" {
					t.Fatalf("%s.%s: decision %q is neither retained nor a redacted reason", method, arg, word)
				}
				out[method][arg] = argumentDecision{}
				continue
			}
			var decision argumentDecision
			if err := json.Unmarshal(value, &decision); err != nil {
				t.Fatalf("%s.%s: unreadable decision: %v", method, arg, err)
			}
			if strings.TrimSpace(decision.Redacted) == "" {
				t.Fatalf("%s.%s: redacted without a reason", method, arg)
			}
			out[method][arg] = decision
		}
	}
	return out
}

// decodedArguments walks a canonical input type for the JSON paths it reads,
// in the dotted form the snapshot uses: touchPoints[].radiusX, bounds.left.
func decodedArguments(t reflect.Type, prefix string) map[string]bool {
	out := map[string]bool{}
	if t == nil || t.Kind() != reflect.Struct {
		return out
	}
	for i := range t.NumField() {
		field := t.Field(i)
		tag := strings.Split(field.Tag.Get("json"), ",")[0]

		// A raw message is read whole to test its presence, not for any
		// argument inside it, so it decodes no canonical argument.
		if field.Type == rawMessageType {
			continue
		}

		inner := field.Type
		suffix := ""
		for inner.Kind() == reflect.Ptr {
			inner = inner.Elem()
		}
		if inner.Kind() == reflect.Slice {
			inner = inner.Elem()
			for inner.Kind() == reflect.Ptr {
				inner = inner.Elem()
			}
			suffix = "[]"
		}

		// An embedded struct contributes its fields at this level.
		if field.Anonymous && tag == "" {
			for path := range decodedArguments(inner, prefix) {
				out[path] = true
			}
			continue
		}
		if tag == "" || tag == "-" {
			continue
		}
		path := prefix + tag

		// A struct read for nothing but its shape — the empty element type used
		// to count a list — yields no canonical argument either.
		if inner.Kind() == reflect.Struct {
			for p := range decodedArguments(inner, path+suffix+".") {
				out[p] = true
			}
			continue
		}
		out[path] = true
	}
	return out
}

func decodedArgumentsFor(method string) map[string]bool {
	proto, ok := commandParams[method]
	if !ok {
		return nil
	}
	return decodedArguments(reflect.TypeOf(proto), "")
}

// Every command the proxy reports must appear in both checked-in files, and
// nothing else may.
func TestManifestCoversExactlyTheSupportedMethods(t *testing.T) {
	snap := loadProtocolSnapshot(t)
	manifest := loadArgumentManifest(t)

	for method := range sanitizers {
		if _, ok := snap.Commands[method]; !ok {
			t.Errorf("%s is reported but absent from the pinned protocol snapshot", method)
		}
		if _, ok := manifest[method]; !ok {
			t.Errorf("%s is reported but has no argument decisions", method)
		}
		if _, ok := commandParams[method]; !ok {
			t.Errorf("%s has no canonical input type registered", method)
		}
	}
	for method := range snap.Commands {
		if _, ok := sanitizers[method]; !ok {
			t.Errorf("%s is in the protocol snapshot but nothing reports it", method)
		}
	}
	for method := range manifest {
		if _, ok := sanitizers[method]; !ok {
			t.Errorf("%s has argument decisions but nothing reports it", method)
		}
	}
}

// The check the OpenAPI-enum comparison could not make: every argument the
// protocol defines for a supported command has an explicit decision, so an
// argument added upstream cannot be silently absent.
func TestEveryCanonicalArgumentHasADecision(t *testing.T) {
	snap := loadProtocolSnapshot(t)
	manifest := loadArgumentManifest(t)

	var undecided []string
	for method, args := range snap.Commands {
		for _, arg := range args {
			if _, ok := manifest[method][arg]; !ok {
				undecided = append(undecided, method+"."+arg)
			}
		}
	}
	sort.Strings(undecided)
	if len(undecided) > 0 {
		t.Fatalf("%d canonical arguments have no retained/redacted decision in %s:\n  %s",
			len(undecided), argumentManifestPath, strings.Join(undecided, "\n  "))
	}

	// And nothing invented: a decision for an argument the protocol does not
	// define is a stale entry, which would hide a rename.
	for method, args := range manifest {
		canonical := map[string]bool{}
		for _, a := range snap.Commands[method] {
			canonical[a] = true
		}
		for arg := range args {
			if !canonical[arg] {
				t.Errorf("%s.%s has a decision but the pinned protocol has no such argument", method, arg)
			}
		}
	}
}

// The decisions have to describe the code: an argument marked retained must be
// decoded, and anything the code decodes must be declared.
func TestManifestDecisionsMatchWhatTheSanitizersDecode(t *testing.T) {
	manifest := loadArgumentManifest(t)

	for method, args := range manifest {
		decoded := decodedArgumentsFor(method)
		for arg, decision := range args {
			retained := decision.Redacted == ""
			switch {
			case retained && !decoded[arg]:
				t.Errorf("%s.%s is marked retained but no canonical input type decodes it", method, arg)
			case !retained && decoded[arg]:
				t.Errorf("%s.%s is marked redacted (%s) but the code decodes it", method, arg, decision.Redacted)
			}
		}
		for arg := range decoded {
			if _, ok := args[arg]; !ok {
				t.Errorf("%s decodes %s, which has no decision recorded", method, arg)
			}
		}
	}
}

// The snapshot names the commit it came from, so a reader can check the
// definitions the decisions were made against.
func TestProtocolSnapshotIsPinned(t *testing.T) {
	snap := loadProtocolSnapshot(t)
	if len(snap.Commit) != 40 {
		t.Fatalf("commit %q is not a full sha, so the snapshot is not pinned", snap.Commit)
	}
	if !strings.Contains(snap.Permalink, snap.Commit) {
		t.Fatalf("permalink %q does not point at the pinned commit", snap.Permalink)
	}
}
