// Code generated by scripts/categorygen; DO NOT EDIT.

package events

import oapi "github.com/kernel/kernel-images/server/lib/oapi"

var categoryByType = map[string]oapi.TelemetryEventCategory{
	"api_call":                   oapi.TelemetryEventCategory("control"),
	"captcha_solve_result":       oapi.TelemetryEventCategory("captcha"),
	"cdp_connect":                oapi.TelemetryEventCategory("connection"),
	"cdp_disconnect":             oapi.TelemetryEventCategory("connection"),
	"console_error":              oapi.TelemetryEventCategory("console"),
	"console_log":                oapi.TelemetryEventCategory("console"),
	"interaction_click":          oapi.TelemetryEventCategory("interaction"),
	"interaction_key":            oapi.TelemetryEventCategory("interaction"),
	"interaction_scroll_settled": oapi.TelemetryEventCategory("interaction"),
	"live_view_connect":          oapi.TelemetryEventCategory("connection"),
	"live_view_disconnect":       oapi.TelemetryEventCategory("connection"),
	"monitor_disconnected":       oapi.TelemetryEventCategory("monitor"),
	"monitor_init_failed":        oapi.TelemetryEventCategory("monitor"),
	"monitor_reconnect_failed":   oapi.TelemetryEventCategory("monitor"),
	"monitor_reconnected":        oapi.TelemetryEventCategory("monitor"),
	"monitor_screenshot":         oapi.TelemetryEventCategory("screenshot"),
	"network_idle":               oapi.TelemetryEventCategory("network"),
	"network_loading_failed":     oapi.TelemetryEventCategory("network"),
	"network_request":            oapi.TelemetryEventCategory("network"),
	"network_response":           oapi.TelemetryEventCategory("network"),
	"page_dom_content_loaded":    oapi.TelemetryEventCategory("page"),
	"page_layout_settled":        oapi.TelemetryEventCategory("page"),
	"page_layout_shift":          oapi.TelemetryEventCategory("page"),
	"page_lcp":                   oapi.TelemetryEventCategory("page"),
	"page_load":                  oapi.TelemetryEventCategory("page"),
	"page_navigation":            oapi.TelemetryEventCategory("page"),
	"page_navigation_settled":    oapi.TelemetryEventCategory("page"),
	"page_tab_opened":            oapi.TelemetryEventCategory("page"),
	"service_crashed":            oapi.TelemetryEventCategory("system"),
	"system_oom_kill":            oapi.TelemetryEventCategory("system"),
}

// CategoryForType returns the authoritative category for a known event
// type. ok is false for an unknown type.
func CategoryForType(eventType string) (oapi.TelemetryEventCategory, bool) {
	c, ok := categoryByType[eventType]
	return c, ok
}
