// Command categorygen derives the authoritative event-type -> category lookup
// from openapi.yaml. Every schema that pins both a `type` const and a
// `category` const contributes one entry. openapi.yaml is the single source of
// truth; this generator just surfaces it to Go.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"

	"gopkg.in/yaml.v3"
)

type property struct {
	Const string `yaml:"const"`
}

type schema struct {
	Properties map[string]property `yaml:"properties"`
}

type document struct {
	Components struct {
		Schemas map[string]schema `yaml:"schemas"`
	} `yaml:"components"`
}

func main() {
	openapiPath := flag.String("openapi", "", "path to openapi.yaml")
	outPath := flag.String("out", "", "path to the generated Go file")
	flag.Parse()
	if *openapiPath == "" || *outPath == "" {
		fmt.Fprintln(os.Stderr, "categorygen: -openapi and -out are required")
		os.Exit(2)
	}

	raw, err := os.ReadFile(*openapiPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "categorygen: read openapi: %v\n", err)
		os.Exit(1)
	}
	var doc document
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		fmt.Fprintf(os.Stderr, "categorygen: parse openapi: %v\n", err)
		os.Exit(1)
	}

	type entry struct{ typ, category string }
	entries := make([]entry, 0, len(doc.Components.Schemas))
	for _, s := range doc.Components.Schemas {
		typ := s.Properties["type"].Const
		category := s.Properties["category"].Const
		if typ != "" && category != "" {
			entries = append(entries, entry{typ, category})
		}
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].typ < entries[j].typ })

	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/categorygen; DO NOT EDIT.\n\n")
	buf.WriteString("package events\n\n")
	buf.WriteString(`import oapi "github.com/kernel/kernel-images/server/lib/oapi"` + "\n\n")
	buf.WriteString("var categoryByType = map[string]oapi.TelemetryEventCategory{\n")
	for _, e := range entries {
		fmt.Fprintf(&buf, "\t%q: oapi.TelemetryEventCategory(%q),\n", e.typ, e.category)
	}
	buf.WriteString("}\n\n")
	buf.WriteString("// CategoryForType returns the authoritative category for a known event\n")
	buf.WriteString("// type. ok is false for an unknown type.\n")
	buf.WriteString("func CategoryForType(eventType string) (oapi.TelemetryEventCategory, bool) {\n")
	buf.WriteString("\tc, ok := categoryByType[eventType]\n")
	buf.WriteString("\treturn c, ok\n")
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "categorygen: format: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "categorygen: write %s: %v\n", *outPath, err)
		os.Exit(1)
	}
}
